name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        env:
           PASSWORD: ${{ secrets.PASS }}
           PROXY_CMD: ${{ secrets.PROXY_CMD }}
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           sshpass -p '$PASSWORD' ssh '$PROXY_CMD' root@192.168.203.12 "kubectl get pods -A" >> report.log 2>&1                    
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
