name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          run: | 
            HOSTNAME=`178.124.206.53` ssh-keygen -t rsa -b 4096 -C "$HOSTNAME" -f "$HOME/.ssh/id_rsa" -P ""
            cat id_rsa.pub > authorized_keys
            chmod 600 authorized_keys
            echo -e "$(cat id_rsa.pub)" >> report.log 2>&1
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
