name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to host with proxy with out password
        id: get_pods
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           echo 'CONTENT_ENV<<EOF' >> $GITHUB_ENV
           ssh ${{ secrets.USERNAME_HOST }}@${{ secrets.HOST_IP }} -o ProxyCommand="ssh -W %h:%p ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }}" -o StrictHostKeyChecking=no "kubectl get pods -A | grep -v Running" | >> $GITHUB_ENV  
           echo 'EOF' >> $GITHUB_ENV
           
      - name: output pods
        id: out_pods    
        run: |        
          echo "$CONTENT_ENV" > report.txt
          if [ report.txt -lt "100" ]
          then          
          echo "$CONTENT_ENV" >> report.log 2>&1
          exit 1
          fi      

          
      - name: Slack Notification
        if: ${{ failure() && steps.out_pods.conclusion == 'failure' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: docker_push
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'We have crashed pods!!!'
          SLACK_TITLE: 'ALERT! Check "echo $(cat report.log)"'
          SLACK_USERNAME: Kostenko Pavel
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
      - name: Upload report
        if: ${{ failure() && steps.out_pods.conclusion == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          path: report.log          

          

