name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: executing remote ssh commands using password
        run: |
           mkdir ~/.ssh
           eval "$(ssh-agent -s)"
           ssh-add - <<< "${{ secrets.KEY }}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           sudo apt-get install sshpass
           sshpass -p${{ secrets.PASS }} ssh jump_sa@178.124.206.53
           #sudo apt-get install sshuttle
           #sshuttle -r ${{secrets.USERNAME_PROXY}}@${{secrets.PROXY_HOST}} 192.168.0.0/16 &
           ls -la
          # sshpass -p ${{ secrets.PASS }} ssh -o ProxyCommand="sshpass ssh -W %h:%p ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }}"         
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
