name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to host with proxy with out password
        id: get_pods
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           #echo 'CONTENT_ENV<<EOF' >> $GITHUB_ENV
           $GITHUB_ENV = ssh ${{ secrets.USERNAME_HOST }}@${{ secrets.HOST_IP }} -o ProxyCommand="ssh -W %h:%p ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }}" -o StrictHostKeyChecking=no "kubectl get pods -A | grep -v Running | grep -v NAMESPACE"   
           #echo 'EOF' >> $GITHUB_ENV
           


      - name: output pods
        id: out_pods    
        run: |        
          echo "$CONTENT_ENV" > report.txt
          echo "$CONTENT_ENV"
          echo ::set-output name=exit_code::$?
          

          
          

      - name: Slack Notification
        if: steps.out_pods.outputs.exit_code == 0 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: docker_push
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'WE have crash'
          SLACK_TITLE: 'ALERT!'
          SLACK_USERNAME: Kostenko Pavel
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
