name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        env:
           PASSWORD: ${{ secrets.PASS }}
           PROXY_CMD: ${{ secrets.PROXY_CMD }}
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/know_hosts
           echo "cat ~/.ssh/know_hosts" 
           ssh root@192.168.203.12 -o ProxyCommand="ssh -W %h:%p jump_sa@178.124.206.53" "kubectl get pods -A" >> report.log 2>&1                    
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
