name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to host with proxy with out password
        id: get_pods
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           echo 'CONTENT_ENV<<EOF' >> $GITHUB_ENV
           ssh ${{ secrets.USERNAME_HOST }}@${{ secrets.HOST_IP }} -o ProxyCommand="ssh -W %h:%p ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }}" -o StrictHostKeyChecking=no "kubectl get pods -A" >> $GITHUB_ENV  
           echo 'EOF' >> $GITHUB_ENV
           


      - name: output pods
        run: |        
          echo "$CONTENT_ENV" >> report.log 2>&1
          


          
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
