name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        run: |
           sshpass -p 'QwertY_13' ssh -o ProxyCommand="ssh -W %h:%p jump_sa@178.124.206.53" root@192.168.203.12 -o StrictHostKeyChecking=no       
           #ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts         
           #ssh -o PreferredAuthentications="${{ secrets.PASS }}" -o PubkeyAuthentication=no ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }} ls -la                 
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
