name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: executing remote ssh commands using password
        run: |
           mkdir ~/.ssh
           cd ~/.ssh
           eval "$(ssh-agent -s)"
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
           ssh ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }} ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
           sshpass -p ${{ secrets.PASSWORD }} 
           ssh -o ProxyCommand="sshpass ssh -W %h:%p ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }}" ${{ secrets.USERNAME_HOST }}@${{ secrets.HOST_IP }} "ls -la" 
         
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
