name: tabs in files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: executing remote ssh commands using password
        run: |
           mkdir ~/.ssh
           eval "$(ssh-agent -s)"
           ssh-add - <<< "${{ secrets.KEY }}"       
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           cat >>~/.ssh/config <<END
           cd ~/.ssh/
           echo "cat config"
          #sshpass -p${{ secrets.PASS }} ssh -f -t -t -t jump_sa@178.124.206.53 ls -la /root/home/                 
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: report.log
